kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suman-kumarsahusu/kubernetes-persneal.git
    targetRevision: main
    path: deployement_strategy/canary
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
