kind: Secret
apiVersion: v1
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
stringData:
  username: "suman-kumarsahusu"
 #password: "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"
  password: "Devops@5770"
