kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: demo
  namespace: argocd
spec:
  description: this was amazing
  sourceRepos:
    - https://github.com/suman-kumarsahusu/argocd-in.git
  destinations:
    - namespace: devops
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"    
  roles:
    - name: demo-role
      description: hello
      policies:
        - p, proj:demo:demo-role, applications, *, demo/*, allow
