kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
      name: imgupdate
      namespace: argocd
      annotations:
        "argocd.argoproj.io/sync-options": "ServerSideApply=true"
        "argocd-image-updater.argoproj.io/image-list": "sumansahudockerhub/online"
        "argocd-image-updater.argoproj.io/write-back-method": "git:secret:argocd/argocd-image-updater-git-creds "
        "argocd-image-updater.argoproj.io/online.update-strategy": "semver"
spec:
  project: default
  source:
      repoURL: https://github.com/suman-kumarsahusu/argocd-in.git
      targetRevision: main
      path: imgupdate/online
  destination:
      server: https://kubernetes.default.svc
      namespace: default
  syncPolicy: 
      automated:
          selfHeal: true
          prune: true
